[package]
name = "btleplug-neon-bindings"
version = "0.1.0"
license = "ISC"
edition = "2018"
exclude = ["index.node"]
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
btleplug = "0.7.2"

[dependencies.neon]
version = "0.8"
default-features = false
features = ["legacy-runtime"]
