[package]
name = "btleplug-neon-bindings"
version = "0.1.0"
license = "ISC"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
btleplug = "0.7.2"
simple_logger = "1.11.0"
uuid = "0.8.2"

[dependencies.neon]
version = "0.8"
default-features = false
features = ["napi-6"]
